server:
  port: 8083
  servlet:
    context-path: /articleapi

spring:
  devtools:
    restart:
      enabled: 'true'
      poll-interval: '2s'
      quiet-period: '1s'
      additional-paths:
      - src/main/kotlin/
