server:
  port: 8081
  servlet:
    context-path: /userapi

spring:
  devtools:
    restart:
      enabled: 'true'
      poll-interval: '2s'
      quiet-period: '1s'
      additional-paths:
        - src/main/kotlin/
